eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name:  trend-trading-backtest-service
# 指定端口
server:
  port: 8051

feign.hystrix.enabled: true